name: Auto Update Date Field for Staged Markdown Files

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main  # 適宜あなたのブランチに変更

jobs:
  update-date-field:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update date in staged Markdown files only
        run: |
          # JSTの現在時刻を取得
          export TZ=Asia/Tokyo
          current_date=$(date +"%Y-%m-%d %H:%M:%S")

          # git push に含まれる直前のコミットで add されたファイルを取得
          added_files=$(git diff --cached --name-only --diff-filter=AM | grep '\.md$' || true)

          for file in $added_files; do
            if [ -f "$file" ] && grep -q '^date: ' "$file"; then
              echo "Updating date in: $file"
              sed -i 's/^date: .*/date: '"$current_date"'/' "$file"
              git add "$file"  # 修正後のファイルを再 add
            fi
          done

      - name: Commit and push changes
        run: |
          git commit -m "Auto-update date field for added Markdown files" || echo "No changes to commit"
          git push
